name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt-core dbt-databricks sqlfluff sqlfluff-templater-dbt

      - name: Lint SQL
        env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
        DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
        ENV: dev
        run: sqlfluff lint dbt/weather/models

      - name: Compile dbt
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
          ENV: dev
        run: dbt compile --project-dir dbt/weather --profiles-dir dbt/weather